[project]
name = "hitchhikers-guide-to-your-local-file-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.4",
    "unstructured[all-docs]>=0.18.9",
]